name: edit-resource

on:
  repository_dispatch:
    types: "edit_resource"

jobs:
  add-resource:
    name: "Edit resource"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update master document and push branch to repository
        run: |
          python scripts/update_master_document.py edit "${{ github.event.client_payload.form_submission }}"
          export timestamp=$(($(date +%s%N)/1000000))
          git branch -m "edit_resource_$timestamp"
          git config user.name "RiC Resource List"
          git config user.email "ric-resource-list@users.noreply.github.com"
          git add master-document/*
          git commit -m "Edit submitted resource"
          git push -u origin "edit_resource_$timestamp"
          gh pr create -B main -H "edit_resource_$timestamp" --title "Edit resource" --body "Submitted via the website."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

